# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aksctx < Formula
  desc "AKS context switcher for discovering and switching clusters across Azure subscriptions"
  homepage "https://github.com/amrinder15/aksctx"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amrinder15/aksctx/releases/download/v0.2.2/aksctx_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "6a3c75c81bad43401f0cef0fb52b93fc59f0790841db14b415338ead88b61710"

      define_method(:install) do
        bin.install "aksctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amrinder15/aksctx/releases/download/v0.2.2/aksctx_0.2.2_Darwin_arm64.tar.gz"
      sha256 "8567ec3cede2a16aed5353a215876630d49d12de1c37c37d3b2f067aa39d3195"

      define_method(:install) do
        bin.install "aksctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amrinder15/aksctx/releases/download/v0.2.2/aksctx_0.2.2_Linux_x86_64.tar.gz"
      sha256 "18c252689928f9de2a159052455762f16de05da63bf76d067d885cea3e3f8d2a"
      define_method(:install) do
        bin.install "aksctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amrinder15/aksctx/releases/download/v0.2.2/aksctx_0.2.2_Linux_arm64.tar.gz"
      sha256 "db65016c9d33854c4484baed394d7d411f7e10b7400e48fa751dae059624a8a9"
      define_method(:install) do
        bin.install "aksctx"
      end
    end
  end

  test do
    system "#{bin}/aksctx", "--help"
  end
end
