# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aksctx < Formula
  desc "AKS context switcher for discovering and switching clusters across Azure subscriptions"
  homepage "https://github.com/amrinder15/aksctx"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amrinder15/aksctx/releases/download/v0.2.1/aksctx_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "572e2bf52163fe741156ce3f293de6652465a7d84164f323f5690caf04f2796e"

      define_method(:install) do
        bin.install "aksctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amrinder15/aksctx/releases/download/v0.2.1/aksctx_0.2.1_Darwin_arm64.tar.gz"
      sha256 "3c4fc3a9c3c3fd3782f85bdc77264441fa6a49e1db1aff1135fada9eb36a519e"

      define_method(:install) do
        bin.install "aksctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amrinder15/aksctx/releases/download/v0.2.1/aksctx_0.2.1_Linux_x86_64.tar.gz"
      sha256 "a249eed92c57715bfdbec80c0617cc059b1b5ab5dd5dc59bef687711c98f7039"
      define_method(:install) do
        bin.install "aksctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amrinder15/aksctx/releases/download/v0.2.1/aksctx_0.2.1_Linux_arm64.tar.gz"
      sha256 "8512a6348c611b876115d47e3ad7c95dc8ec55290671e8a8d69f69ff63a77332"
      define_method(:install) do
        bin.install "aksctx"
      end
    end
  end

  test do
    system "#{bin}/aksctx", "--help"
  end
end
